### ISSUE TITLE
a couple of graphical issues

### ISSUE THREAD

**Issue by chee** [BarkyTheDog/catclock#1]
hello, it is my dream to have a catclock

![blockclock](https://cloud.githubusercontent.com/assets/178266/21247278/33cc188e-c326-11e6-9323-37348000d71d.png)

when i compile on linux (arch linux, latest everything) catclock starts up like this :(

at the moment i'm still running a dedicated plan9 virtual machine for catclock until such a time as i can get this working

one time i ran it (did nothing different) and it looked like this instead:

![darkcat](https://cloud.githubusercontent.com/assets/178266/21247316/80b1e1b0-c326-11e6-9117-a7f09540a05c.png)
 

any ideas?

**Comment by chee** [comment]
oh no, i'm not trying to run `xclock -mode catclock` under a virtual machine. i just normally use a virtual machine for plan9's sys/games/catclock and this would mean i didn't have to.

this problem is happening on a regular arch linux system, running on bare metal, and it's happening whether compiled with lesstif or openmotif.

the red border is actually just me not cropping the screenshot properly, that's my desktop background. leaking through

yes, x11 certainly does not enjoy being told to draw oddly shaped things. though my only experience with it is in writing a window manager.

**Comment by BarkyTheDog** [comment]
OK, I see that I misunderstood your situation. My apologies. In that case, perhaps there’s a chance at figuring out what’s going on (maybe a workaround of some sort).

Can you give me specifics on your configuration:
- Linux distro and version
- X11/Xt/Motif/Lesstif versions
- Machine info

Can’t promise anything, but if I could replicate the bug… :-)

**Comment by chee** [comment]
linux distro: arch linux
x11: 1.18.4
lesstif:  0.95.2
machine: macbook pro 13 inch retina

**Comment by Happy-Ferret** [comment]
Hi there.
Just stumbled upon this bug when I was researching a potential feature patch (I thought about implementing FIFO, so users can customise the clock without restarting it. That's not possible without a patch, right?)

Just an idea but are you running Wayland as your primary session, perhaps? Sounds like it might be a bug in xwayland.

I don't have an arch machine but catclock(1) is running fine on all my devices, so far. That includes my Windows 10 workstation at the office.

**Comment by chee** [comment]
Hey, no i'm still on xorg because i'm not willing to accept the future and i cry when my toys are taken away

**Comment by RamKromberg** [comment]
@chee Works fine with the latest motif under NixOS.

**Comment by chee** [comment]
i just got a thinkpad x220 and it works fine on there with lesstif. throwing the macbook away in a fire or bin

thanks 

thanks everybody

theanks
