### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by hansonchar** [BarkyTheDog/catclock#6]
Thank you for this fun app! 

1. How can the background color of the cat be set to gray as shown in your demo image?  There doesn't seem to be a parameter on this, and currently it's using white as the default. Here is what I got so far on my Apple M2 under Sonoma 14.5:

    ![Screenshot 2024-05-21 at 12 15 08 PM](https://github.com/BarkyTheDog/catclock/assets/719633/b81a06a1-641f-44b8-be75-c1fde40cc42a)

2. A related question - can the background color be set to transparent, similar to `xeyes`?  Attached an example below.
    
    ![Screenshot 2024-05-21 at 12 17 03 PM](https://github.com/BarkyTheDog/catclock/assets/719633/4b7b4a0d-8980-455c-822b-c99f31723f51)

**Comment by hansonchar** [comment]
Figured it out.  It's supported via the standard X11 toolkit option.  So something like `-background gray` would do it.

Thanks again for this cute app!

**Comment by BarkyTheDog** [comment]
Glad you found this antique app amusing. I find it hilarious that it can still be compiled and run these days.Regarding the transparent background: I vaguely recall looking into that quite a few years ago. The X11 extension that I think supports what xeyes shows (https://www.x.org/releases/X11R7.7/doc/xextproto/shape.html) wasn’t really created to support a dynamically changing window shape. IIRC  it didn’t play well (or work at all?)  with the tail animation. I think what would be needed would to be able to specify a “clear” background color that the window system renderer would need to respect?- PhilipOn May 21, 2024, at 3:38 PM, Hanson Char ***@***.***> wrote:﻿
Figured it out.  It's supported via the standard X11 toolkit option.  So something like -background gray would do it.
Thanks again for this cute app!
